language: php
php:
  - 7.1
  - 7.2
  - 7.3
env:
  - WP_MULTISITE: 0
  - WP_MULTISITE: 1
install:
  - composer install
  - bash tests/install-tests.sh wordpress_test root '' 127.0.0.1 latest
script:
  - phpunit
notifications:
    email: false
