language: php
php:
  - '7.2'
services:
  - mysql
install:
  - composer install
  - bash tests/install-tests.sh wordpress_test root '' 127.0.0.1 latest
script:
  - vendor/bin/phpunit --exclude-group cron
notifications:
    email: false
