language: php
php:
  - '7.2'
services:
  - mysql
install:
  - composer install
  - bash tests/install-tests.sh wordpress_test root '' 127.0.0.1 latest
script:
  # 32656 tests are related to the pre_*_event filters which we're using already
  # 45976 tests compare event objects directly, cavalcade adds the _job property
  - vendor/bin/phpunit --exclude-group 32656,45976
notifications:
    email: false
